version: '3'

services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./frontend/dist:/www/static
  node-api:
    image: yuan126/rtmp-node-api
    build: ./backend
    ports:
      - 5000:5000